-- Copyright 2025 Niklas Glienke

BEGIN TRANSACTION;

INSERT INTO "brevity_term" ("term", "description", "used_in_digest") VALUES
    ("ABORT", "Cease action or terminate the attack prior to weapons release or event or mission.", 0),
    ("ACTION", "[A/A] [A/S] [S/A] [AIR-MAR] Initiate a briefed attack sequence or maneuver.", 0),
    ("ALARM", "[A/A] [EW] [MAR] [SO] Terminate or terminating emissions control procedures. Opposite of SNOOZE.", 0),
    ("ALPHA CHECK", "* Request for confirmation of bearing and range from aircraft to described point.", 0),
    ("ANCHOR [location]", "1. Orbit about a specific point. & 2. Refueling track flown by tanker.", 0),
    ("ANCHORED [location]", "* [A/A] Turning engagement at the specified location", 0),
    ("ANGELS", "Height of FRIENDLY aircraft in thousands of feet from mean sea level (MSL).", 0),
    ("ARIZONA", "[A/S] [EW] No antiradiation missile ordnance remaining.", 0),
    ("ARMSTRONG", "** Directive call to set the MASTER ARM switch to ARM.", 0),
    ("AS FRAGGED", "* Unit or element will be performing exactly as briefed or scheduled.", 0),
    ("ATTACK", "* [A/S] An informative call indicating aircraft are committed to air-to-surface delivery on a specific ground target.", 0),
    ("[number, weapon type] AWAY", "[A/S] [AIR-MAR] [S/A] Release or launch of specified weapon (e.g., 1 AWAY, 2 PIGS AWAY, BIRDS AWAY, etc.). At minimum number or weapon type required.", 0),
    ("BANDIT", "[A/A] [AIR-MAR] Positively identified as an enemy in accordance with (IAW) theater ID criteria. The term does not imply direction or authority to engage.", 0),
    ("BANZAI", "* [A/A] Execute(ing) launch and decide tactics with the intent to maneuver into the visual arena.", 0),
    ("[system] BENT", "System indicated is inoperative. Cancelled by SWEET.", 0),
    ("BINGO", "* Prebriefed fuel state needed for recovery.", 0),
    ("BLACKOUT", "** 1. [A/A] Turn off all external lighting.", 0),
    ("BLIND", "No visual contact with FRIENDLY aircraft, ship, or ground position. Opposite of VISUAL.", 0),
    ("BLOW THROUGH", "[A/A] Continue straight ahead at the MERGE and do not become ANCHORED with target(s).", 0),
    ("BLOWING THROUGH", "[A/A] Intercepting aircraft is dropping targeting responsibility and commencing a BLOW THROUGH.", 0),
    ("BLUR", "** Radar being jammed.", 0),
    ("BOGEY", "[A/A] [S/A] [SO] A CONTACT whose identity is unknown.", 0),
    ("BOGEY DOPE", "[A/A] [S/A] Request for information on indicated or closest GROUP in bearing, range, altitude, and aspect (BRAA) format (with appropriate fillins).", 0),
    ("BRAA", "[A/A] [S/A] 1. Provides target BRAA relative to the specified FRIENDLY aircraft (tactical control format). & 2. Switch to BRAA format to a specific GROUP or CONTACT.", 0),
    ("BREAK [direction]", "[A/A] Perform an immediate maximum performance turn in the indicated direction (default is a 180-degree turn).", 0),
    ("BREAK AWAY", "Tanker or receiver call indicating immediate vertical and nose-to-tail separation between tanker and receiver is required.", 0),
    ("BRUISER", "* [AIR-MAR] [A/S] Employment of FRIENDLY air- launched, short range, subsonic anti-ship weapon(s). Option to add follow-on modifiers for number of munitions and/or time of flight.", 0),
    ("BUDDY [LASE or GUIDE]", "* [A/S] Have weapon guidance from a source other than delivering aircraft.", 0),
    ("BUDDY SPIKE", "[A/A] FRIENDLY system radar lock-on indication on radar warning receiver.", 0),
    ("BULLSEYE", "An established reference point from which the position of an object can be referenced by bearing (magnetic) and range (nautical miles) from this point.", 0),
    ("BUTTON", "Radio channel setting.", 0),
    ("CAP(ING) [location]", "1. [A/A] Establish a combat air patrol at a specified point, used prior to committing forces in support of a defensive operation. & 2. [A/A] Aircraft is established in an orbit.", 0),
    ("[target or object] CAPTURED", "* [A/S] Object has been acquired and is being tracked.", 0),
    ("CEASE [activity]", "* Discontinue stated activity; e.g., CEASE BUZZER, LASER, SPARKLE, TORCH, etc.", 0),
    ("CEASE FIRE", "Stop firing, do not open fire. Missiles in flight will continue to intercept; continue to track.", 0),
    ("CHARLIE", "1. [AIR-MAR] A signal to land aboard the ship. & 2. A number suffix indicates a time delay in minutes before the landing is anticipated (e.g., CHARLIE ten).", 0),
    ("CHECK [number, left or right]", "* [A/A] Turn (number) degrees left or right and maintain new heading.", 0),
    ("CHERUBS", "Height of a FRIENDLY aircraft in hundreds of feet above ground level.", 0),
    ("CHICK(S)", "* Term used to denote FRIENDLY aircraft on the safe flight or mission.", 0),
    ("CHRISTMAS TREE", "** [A/A] Turn on all external lighting.", 0),
    ("CLEAN", "1. [A/A] No sensor information on a GROUP of interest. & 2. No visible battle damage. & 3. Aircraft not carrying external stores.", 0),
    ("CLEARED", "Requested action is authorized.", 0),
    ("CLEARED HOT", "[A/S] Term used by a joint terminal attack controller (JTAC) / forward air controller (airborne) (FAC(A)) during Type 1 and 2 CAS terminal attack control when granting weapons release clearance to an aircraft attacking a specific target.", 0),
    ("CLEARED TO ENGAGE", "1. ** [A/S] Term used by a JTAC/(FAC(A) during Type 3 control, granting a weapons release clearance to an aircraft or flight to attack a target or targets within the parameters prescribed by the JTAC/FAC(A). & 2. ** [A/A] [A/S] Clearance to fire on designated GROUP or target.", 0),
    ("CLOSING", "[A/A] Decreasing separation.", 0),
    ("COLD", "1. [A/A] Initiate(ing) a turn in the combat air patrol away from the anticipated threats. & 2. * [A/S] Defined area is not expected to receive fire (enemy or FRIENDLY). & 3. [A/A] Intercept geometry will result in a pass or roll out behind the target. & 4. * [A/A] [AIR-MAR] Contact aspect stabilized 0–20 degrees from the tail or 160–180 degrees from the nose (or from the stern or bow for a ship respectively). & 5. * [A/S] Contact aspect stabilized 0-20 degrees or 160-180 degrees from referenced position (friendly forward operating base, named area of interest, target area, etc.).", 0),
    ("COMMIT", "1. * [A/A] Intercept the GROUP(S) of interest. & 2. * [A/A] Set briefed intercept geometry.", 0),
    ("CONS/CONNING", "* [A/A] Aircraft producing contrails.", 0),
    ("CONTACT(S)", "1. Sensor information at the stated position. & 2. [A/S] Acknowledges sighting of a specified reference point (either visually or via sensor). & 3. [A/A] Individual radar return within a GROUP or ARM.", 0),
    ("CONTINUE", "Continue present maneuver, does not imply a change in clearance to engage or expend ordnance.", 0),
    ("CONTINUE DRY", "[A/S] Continue present maneuver, ordnance release not authorized. Used to provide approval to aircraft to continue the pass without expending ordnance during Type 1, 2, or 3 control. (JTAC must use “Type 3, CONTINUE DRY” for dry Type 3 control).", 0),
    ("CRANK [direction]", "[A/A] Maneuver in the direction indicated. Implies illuminating target at or near radar GIMBAL limits.", 0),
    ("DASH [number]", "Aircraft position within a flight. Use if specific call sign is unknown.", 0),
    ("DECLARE", "* [A/A] [S/A] [AIR-MAR] Inquiry as to the ID of a specified track(s), target(s), or correlated GROUP. Responses include: FRIENDLY, BOGEY, BANDIT, HOSTILE, NEUTRAL, UNABLE, CLEAN, or FURBALL. Full positional data (BULLSEYE) or TRACK NUMBER must accompany responses.", 0),
    ("DEFENDING [direction]", "[A/A] [A/S] Aircraft is in a defensive position and maneuvering with reference to a SAM threat.", 0),
    ("DEFENSIVE", "[A/A] [A/S] Aircraft is under attack, maneuvering defensively, and unable to ensure deconfliction or mutual support.", 0),
    ("DIRT", "** [S/A] Radar warning receiver indication of surface threat in search mode. See MUD and SINGER.", 0),
    ("DIRTY", "1. * [A/A] Aircraft in landing configuration. & 2. * [A/A] Aircraft equipped with external stores (i.e., “DIRTY wings”).", 0),
    ("DIVERT", "Proceed to alternate base.", 0),
    ("DRAG [cardinal direction]", "* [A/A] Contact aspect stabilized at 0–60 degrees angle from tail or 120–180 degrees angle from nose.", 0),
    ("ENGAGE", "A fire control order used to direct or authorize units to fire on a designated target.", 0),
    ("ENGAGED", "[A/A] Call from an aircraft maneuvering in the visual arena to relinquish deconfliction responsibilities.", 0),
    ("ENGAGEMENT COMPLETE", "** [A/S] Mandatory call from the attack aircraft to the JTAC or FAC(A) during Type 3 CAS terminal control indicating completion of ordnance release. See also CLEARED TO ENGAGE.", 0),
    ("EXTEND(ING) [direction]", "[A/A] [A/S] Short-term maneuver to gain energy, distance, or separation with the intent of reengaging.", 0),
    ("EYEBALL", "[A/A] Fighter with primary visual ID responsibility. See SHOOTER", 0),
    ("FADED", "* [A/A] [S/A] [AIR-MAR] Sensor data is lost on GROUP or CONTACT. Requires information of last known position to include number of CONTACTS and TRACK direction.", 0),
    ("FAKER", "[A/A] [AIR-MAR] A FRIENDLY track acting as a HOSTILE for exercise purposes", 0),
    ("FATHER", "* [AIR-MAR] Surface tactical air navigation station.", 0),
    ("FEET WET/DRY", "Flying over water or land.", 0),
    ("FENCE [IN/OUT]", "Set cockpit switches as appropriate before entering or exiting the combat area.", 0),
    ("FLANK [direction]", "* [A/A] CONTACT aspect stabilized at 120–150 degrees angle from tail or 30–60 degrees angle from nose.", 0),
    ("FLASH", "1. [A/A] [state system] Temporarily activate specified system for ID purposes (identification, friend or foe (IFF)), or afterburner, flare or chaff, etc.). & 2. * Clear the net immediately, critical information to follow (e.g., “FLASH, FLASH, FLASH this is Frontier 6, immediate MEDEVAC, grid to follow.”).", 0),
    ("FLOW [direction or heading]", "[A/A] Maneuver in stated direction or heading. Can be used to begin cold operations.", 0),
    ("FLY-BY", "** [A/S] [AIR-MAR] Aircraft conduct low altitude pass abeam or overhead the vessel or location. See THUMP, PEPPER.", 0),
    ("FOX [number]", "[A/A] Simulated or actual launch of air-to-air weapons. & (ONE): Semi-active radar-guided missile. & (TWO): IR-guided missile. & (THREE): Active radar-guided missile.", 0),
    ("[2nd] FOX THREE/TWO/ONE [number] SHIP", "[A/A] Simulated or actual missile launch against separate targets (assumes one missile per target) (e.g., “SWORD 12, FOX THREE 2 SHIP”). When 2nd prefix is used indicates simulated or actual launch of multiple missiles on the same target.", 0),
    ("FRIENDLY", "** A positively identified FRIENDLY aircraft, ship, spacecraft, or ground position.", 0),
    ("FUEL STATE [time or pounds]", "* Aircraft fuel quantity, expressed in time or pounds, remaining until BINGO. FUEL STATE can be used as request for information. “FUEL STATE [time or pounds]” represents current status of platform.", 0),
    ("FUMBLE", "[A/A] [A/S] Observed weapons missing target or impacting without desired weapons effects (DWE).", 0),
    ("FURBALL", "1. [A/A] Non-FRIENDLY aircraft and FRIENDLY aircraft are inside of 5 nautical miles of each other. Can be response to a DECLARE request. & 2. * [SO] Spacecraft are so close together that off-board sensors cannot distinguish relative positions.", 0),
    ("GATE", "Fly as quickly as possible, using after-burner or maximum power.", 0),
    ("GOGGLE/DE-GOGGLE", "** [A/A] [A/S] Directive call for aircrew to put on or take off night vision-goggles.", 0),
    ("GOGGLES [on/off]", "* [A/A] [A/S] An informative call that nightvision goggles are on/off.", 0),
    ("GORILLA", "[A/A] [AIR-MAR] [S/A] Large force of indeterminate numbers and formation of unknown or non-friendly aircraft.", 0),
    ("GRANDSLAM", "All HOSTILE CONTACT(S) of a designated track (or against which a mission was tasked) are destroyed.", 0),
    ("GROUP", "1. [A/A] Any number of air CONTACT(S) within 3 nautical miles in azimuth and range of each other. & 2. * [AIR-MAR] Any number of surface CONTACTS within 1 nautical mile of each other.", 0),
    ("GUNS", "[A/A] [A/S] Aircraft gun is being employed.", 0),
    ("HARD [left, right, direction]", "High-G-force, energy sustaining turn in the indicated direction (default is a 180-degree turn).", 0),
    ("HEADS UP", "Alert of an activity of interest.", 0),
    ("HEAVY", "[A/A] [AIR-MAR] A GROUP known to contain three or more CONTACTS.", 0),
    ("HIT(S)", "1. Radar return(s). & 2. * Weapons had desired effects on the intended target.", 0),
    ("HOLD FIRE", "* An emergency fire control order to stop firing on a designated target and destroy missiles in flight.", 0),
    ("HOLDING HANDS", "* [A/A] Aircraft in visual formation", 0),
    ("HOME PLATE", "Home airfield or ship.", 0),
    ("HOOK", "1. [A/A] (direction) Perform an in-place, 180-degree turn.", 0),
    ("HOSTILE", "** A contact identified as enemy upon which clearance to fire is authorized IAW theater rules of engagement (ROE).", 0),
    ("HOT", "1. [A/A] Initiate or initiating a turn in the combat air patrol toward the anticipated threats. & 2. * CONTACT aspect stabilized at 160–180 degrees angle from tail or 0–20 degrees angle from nose. & 3. Defined area is expected to receive fire (enemy or FRIENDLY).", 0),
    ("ID", "1. [A/A] [AIR-MAR] Directive call to identify the target or track. & 2. [A/A] (type) ID is accomplished, followed by type.", 0),
    ("IDLE", "Surface vehicles and/or vessels are stationary.", 0),
    ("IMPACT [time]", "1. [A/S] Weapons observed impacting with unknown effects. & 2. Preemptive call with estimated time of impact.", 0),
    ("IN [direction]", "1. [A/A] Turning toward a known threat. Opposite of OUT. & 2. [A/S] Entering terminal phase of an air-toground attack. Opposite of OFF.", 0),
    ("IN PLACE [direction]", "[A/A] Perform indicated maneuver simultaneously.", 0),
    ("IN THE BLIND", "** A radio term indicating an agency/aircraft/unit is transmitting without having established two way communications with desired participants. May be utilized if experiencing radio jamming.", 0),
    ("INVESTIGATE", "1. [A/S] Verify specified element(s) of rules of engagement (ROE), positive identification (PID), collateral damage estimation (CDE), and/or coordination of forces on the referenced target or track. & 2. ** [AIR-MAR] Verify specified element(s) of ROE, PID, clear field of fire, and/or coordination of forces on the referenced target or track.", 0),
    ("JAM", "** [EW] Directive call to initiate jamming", 0),
    ("JINK", "[A/A] [A/S] Perform an unpredictable maneuver to negate a tracking solution.", 0),
    ("JOKER", "*Fuel state above BINGO at which separation, BUGOUT, or event termination should begin.", 0),
    ("KICK [appropriate frequency]", "* Change radio or data link to a specified net or frequency, typically used for an unplanned change in frequency (e.g., CHATTERMARK). Also see PUSH.", 0),
    ("KILL", "* [A/A] [S/A] In training, shooters are TALLY at assessed missile timeout.", 0),
    ("KNOCK-IT-OFF", "[A/A] [A/S] Cease all air combat maneuvers, attacks, activities, or exercises (training use only).", 0),
    ("LASER ON", "[A/S] [S/S] Directive call to start lasing.", 0),
    ("LASING", "[A/S] [S/S] The speaker is firing the laser in response to LASER ON.", 0),
    ("LEAD-TRAIL", "[A/A] [A/S] [AIR-MAR] Inner GROUP formation of two CONTACTS separated in range.", 0),
    ("LEAKER(S)", "[A/A] [S/A] [AIR-MAR] Airborne threat has passed through a defensive layer. Call should include amplifying information.", 0),
    ("LEVEL", "1. Contact is co-altitude (inter-flight call). & 2.** Briefed altitude has been reached.", 0),
    ("LINE ABREAST", "[A/A] [AIR-MAR] Inner GROUP formation of two or more contacts separated in azimuth.", 0),
    ("LOCKED", "1. [A/A] (with GROUP label) Radar lock-on; SORT is not assumed. & 2. [A/A] (with position) Radar lock-on; correct targeting is not assumed.", 0),
    ("LONG RIFLE", "** [A/S] Employment of long range air-to-surface munition with sustained propulsion (e.g., air-launched cruise missile). Option to add follow-on modifiers for number of munitions and/or time of flight.", 0),
    ("LOOKING", "[A/S] [AIR-MAR] Aircrew does not have the ground or surface object, reference point, or target in sight (opposite of CONTACT).", 0),
    ("LOST LOCK", "* [A/A] Loss of host radar or IR lock-on.", 0),
    ("MAGNUM [system, location]", "[A/S] [EW] Launch of FRIENDLY antiradiation missile.", 0),
    ("MARK", "1. Record the location of a point or object of interest. & 2. ** [A/A] Challenge and response term for requested aircraft to report contrails.", 0),
    ("MARSHAL(LING)", "Establish(ing) at a specific point, typically used to posture forces in preparation for an offensive operation.", 0),
    ("MELD", "1. * [A/A] Bias radar coverage IAW briefed parameters. & 2. * [A/A] Shift radar responsibilities from sanitizing to gaining situational awareness on the assigned GROUP.", 0),
    ("MERGE", "[A/A] FRIENDLIES and targets have arrived in the visual arena.", 0),
    ("MILLER TIME", "[A/S] Completion of A/S ordnance delivery. Generally used by the last striker in conjunction with a precoordinated egress plan.", 0),
    ("MINIMIZE", "The radio frequency is becoming saturated, degraded, or jammed and briefer transmissions must follow.", 0),
    ("MISSILE LAUNCH [direction]", "* [A/A] Radar warning receiver indication or visual on enemy launched A/A Missile.", 0),
    ("MONITOR(ING) [GROUP or object]", "1. [A/A] [A/S] Maintain(ing) sensor awareness on specified GROUP or object. Implies that tactically significant changes will be communicated. & 2. * [AIR-MAR] Maintain contact or targeting information on a maritime surface contact.", 0),
    ("MOTHER", "[AIR-MAR] Parent ship.", 0),
    ("MUD [type with direction, range if able]", "1. [A/S] [EW] Radar warning receiver ground threat displayed with no launch indication. & 2. * [A/S] [EW] Radar warning receiver indication of surface threat in track mode. See DIRT and SINGER.", 0),
    ("MUSIC", "* [A/A] Radar electromagnetic deceptive jamming.", 0),
    ("NAILS [direction]", "1. [A/A] Radar warning receiver indication of airborne interceptor radar in search.", 0),
    ("NAKED", "[A/A] No radar warning receiver indications.", 0),
    ("NEGATIVE LASER", "[A/S] Laser energy has not been acquired.", 0),
    ("NEUTRAL", "** A positively identified aircraft, ship, or ground position whose characteristics, behavior, origin, or nationality indicate it is neither supporting nor opposing FRIENDLY forces.", 0),
    ("NEW PICTURE", "[A/A] [A/S] [AIR-MAR] Used by controller or aircrew when tactical PICTURE has changed. Supersedes all previous calls and reestablishes PICTURE for all players.", 0),
    ("[object] NO FACTOR", "[A/A] [A/S] [S/A] Stated [object] is not a threat.", 0),
    ("NO JOY", "1.* [A/A] [A/S] [S/A] [SO] Aircrew does not have visual contact with the TARGET or BANDIT. Opposite of TALLY. & 2. * Indicates that radio communications could not be established with the distant end on a specified radio net.", 0),
    ("NOSE HOT/COLD", "** RADAR turned ON/OFF.", 0),
    ("NOTCH(ING) [direction]", "* [A/A] [A/S] [S/A] Aircraft is in a defensive position. Maneuver(ing) with reference to a threat.", 0),
    ("OFF [direction]", "[A/A] [A/S] Attack is terminated, and maneuvering to the indicated direction.", 0),
    ("OFFSET [direction]", "Maneuver in a specified direction with reference to the target.", 0),
    ("ON TOP [altitude]", "Informative call when above clouds, following POPEYE.", 0),
    ("OUT [direction]", "[A/A] Directive call indicating a turn to a cold aspect relative to the known threat. Used in launch-and-leave tactics and for all flight members to execute.", 0),
    ("PADLOCKED", "Aircrew cannot take eyes off an aircraft, ground target, or surface position without risk of losing TALLY or VISUAL.", 0),
    ("PANCAKE", "Land or request to land (reason may be specified; e.g., PANCAKE AMMO, PANCAKE FUEL).", 0),
    ("PARROT", "IFF Transponder.", 0),
    ("PASSING", "[A/A] Two GROUPs initially separated in range, decrease range separation and are passing each other.", 0),
    ("PEPPER", "* [AIR-MAR] Directive call for an aircraft to strafe 1,000 ft ahead of the bow of a vessel.", 0),
    ("PICTURE", "* [A/A] [A/S] [AIR-MAR] A request to provide information pertinent to the mission in a digital bullseye format unless briefed otherwise.", 0),
    ("PIG(S)", "[A/S] FRIENDLY glide weapon(s) (e.g., standoff weapon, guided bomb unit, small diameter bomb). See (weapon) AWAY.", 0),
    ("PINCE", "[A/A] Threat maneuvering for a bracket attack.", 0),
    ("PLAYTIME", "Amount of time aircraft can remain on station, given in hours plus minutes (e.g., ONE PLUS THIRTY equals 1 hour and 30 minutes).", 0),
    ("POP", "1. [A/S] Starting climb for A/S attack. & 2. [A/A] Maximum performance climb out of lowaltitude structure.", 0),
    ("POPEYE [altitude]", "1. Flying in clouds or an area of reduced visibility. & 2. * Reduced EO/IR visibility due to atmospherics.", 0),
    ("POP-UP", "* [A/A] GROUP that has suddenly appeared between the MELD and threat range.", 0),
    ("POSIT", "Request for FRIENDLY position; response in terms of a geographic landmark or from a common reference point.", 0),
    ("PUMP", "* [A/A] A briefed maneuver to minimize closure on the threat or geographical boundary with the intent to reengage.", 0),
    ("PURE", "[A/A] Pure pursuit is being used or a directive to go pure pursuit.", 0),
    ("PUSH [channel]", "Switch to designated frequency; no acknowledgment required.", 0),
    ("PUSHING", "[A/A] Departing designated point.", 0),
    ("RAYGUN [position, heading, altitude]", "1. [A/A] Radar lock-on to unknown aircraft. & 2. [A/A] A request for a BUDDY SPIKE reply from FRIENDLY aircraft meeting these parameters.", 0),
    ("RE-CYCLE [system]", "** Directive call for aircrew to turn IFF or selective ID feature or specified system off and on.", 0),
    ("REFERENCE [direction or heading]", "Assume stated direction or heading.", 0),
    ("REMINGTON", "** [A/A] [A/S] No ordnance remaining except gun or self-protection ammo.", 0),
    ("REPEAT", "1. ** [S/S] (during adjustment) Fire again using the same method and volume of fire. & 2. ** [S/S] (during fire for effect) Fire the same number of rounds using the same method and volume of fire.", 0),
    ("RESET", "[A/A] [S/A] [SO] Proceed to a prebriefed position or area of operations.", 0),
    ("RESUME", "[A/A] Resume last formation, route, or mission ordered.", 0),
    ("RETROGRADE (ING)", "* Withdraw(ing) while executing defensive procedures in response to a threat.", 0),
    ("RIFLE [number, time]", "* [A/S] [AIR-MAR] FRIENDLY A/S missile launch. Option to add follow-on modifiers for number of munitions and/or time of flight.", 0),
    ("RIPPLE", "[A/S] [S/A] [AIR-MAR] Two or more munitions will be released or fired in close succession. Typically associated with number and type of weapon with release interval. (Normally discussed during the prestrike game plan between aircraft and/or between aircraft and ground tactical controller).", 0),
    ("ROBBER", "** [AIR-MAR] A surface vessel that is identified as an enemy IAW theater ID criteria. The term does not necessarily imply clearance to engage.", 0),
    ("ROGER", "Radio transmission received; does not indicate compliance or reaction.", 0),
    ("ROLEX [+/- time]", "Timeline adjustment in minutes for entire mission; always referenced from original preplanned mission execution time. “Plus” means later; “minus” means earlier.", 0),
    ("SADDLED/SETTLED [position]", "[A/A] Wingman or element has returned to briefed formation position.", 0),
    ("SAM [direction]", "Visual acquisition of a SAM in flight or a SAM launch; should include position.", 0),
    ("SAME", "Aircrew has the identical information as was just stated.", 0),
    ("SANDWICHED", "[A/A] Aircraft or element is between opposing aircraft or elements.", 0),
    ("SATURATED", "** [S/A] Weapons system radar has exhausted all resources. Ability to detect new tracks is minimal.", 0),
    ("SCAN", "[A/S] Search sector indicated and report any CONTACTS.", 0),
    ("SCORPION", "** [S/A] Enemy man-portable air defense system (MANPADS).", 0),
    ("SCRAMBLE", "[A/A] [S/A] [S/S] Takeoff as quickly as possible.", 0),
    ("SEAD", "** [A/S] Execute the contracts of prebriefed suppression of enemy air defenses (SEAD).", 0),
    ("SET", "Set (or have set) a particular speed. May be indicated in knots or Mach.", 0),
    ("SHACKLE", "[A/A] One weave; a single crossing of flight paths; maneuver to adjust or regain formation parameters.", 0),
    ("SHADOW", "Follow indicated TARGET.", 0),
    ("SHOOT", "** [A/A] Directive communication to employ weapons on a contact, does not invoke targeting.", 0),
    ("SHOOTER", "Aircraft or unit designated to employ ordnance. See EYEBALL", 0),
    ("SHOT", "** [S/S] Round(s) has/have been fired.", 0),
    ("[system] SICK", "** System indicated is degraded or partially operative. Canceled by SWEET.", 0),
    ("[system] SILENT", "1. [A/A] (time) System will be unavailable for time indicated. & 2. Data link is, or should be placed, in receive only. & 3. [EW] Broadcast station is not transmitting. May also be used as an order and must be followed by a frequency or station designator. If possible, it should be followed by an estimated time of return to the air.", 0),
    ("SINGER [type, direction]", "[EW] Radar warning receiver indication of SAM launch. See MUD and DIRT.", 0),
    ("SINGLE", "[A/A] [AIR-MAR] One GROUP, CONTACT, etc.", 0),
    ("SKATE [LONG/SHORT]", "[A/A] Call to execute launch and leave tactics at a prebriefed range. Modifiers can include LONG and SHORT.", 0),
    ("SKIP IT", "Directive call for a specific platform to not engage the indicated track. Usually followed with further directions.", 0),
    ("SKOSH", "[A/A] Aircraft is out of or unable to employ active radar guided missiles.", 0),
    ("SKUNK", "* [A/S] [AIR-MAR] A maritime or ground CONTACT that has not yet been identified.", 0),
    ("SLAPSHOT [type, bearing]", "[A/S] [EW] Immediately employ a best available antiradiation missile against a specified threat at the specified bearing.", 0),
    ("SLICE / SLICEBACK [left/right]", "[A/A] Perform a high-G descending turn in the stated direction, usually 180-degree turn.", 0),
    ("SMOKE", "[A/S] Smoke marker used to mark a position.", 0),
    ("SNIPER [type, location (range, bearing)]", "[A/S] [EW] Aircraft to employ a range known antiradiation missile against a specified threat at the specified location.", 0),
    ("SNOOZE", "[A/A] [EW] [SO] Initiate(ing) emission control procedures. Opposite of ALARM.", 0),
    ("SORT", "1. [A/A] Assignment of responsibility within a GROUP; criteria can be met visually, electromagnetically (i.e., radar), or both. & 2. * [A/S] Assignment of specific targeting responsibilities.", 0),
    ("SORTED", "[A/A] [A/S] [AIR-MAR] Sort responsibility within a GROUP has been met.", 0),
    ("[system] SOUR", "1. (mode/type) [A/A] [S/A] Invalid or no response to an administrative IFF or selective ID feature check. & 2. (link name) (e.g., 'TIMBER SOUR') Potential problems with net entry; initiates pre-mission link troubleshooting. (Opposite of SWEET)", 0),
    ("SPIKE [direction]", "* [A/A] [S/A] Radar warning receiver indication of an air or SAM threat in track or launch.", 0),
    ("SPIN", "[A/A] Execute(ing) a timing or spacing maneuver.", 0),
    ("SPLASH(ED)", "1. [A/A] [A/S] [S/A] Hit observed with valid DWE against a target. & 2. * [S/A] [S/S] Informative call to observer or spotter 5 seconds prior to estimated time of impact.", 0),
    ("SPOT", "1. [A/S] Acquisition of the reflected laser energy. & 2. Platform is laser spot tracker capable.", 0),
    ("SQUAWK [mode, code]", "[A/A] Operate IFF/selective ID feature as indicated or IFF or selective ID feature is operating as indicated.", 0),
    ("SQUAWKING [mode number", "* [A/A] [S/A] BOGEY is responding with an IFF or selective ID feature mode or code other than that prescribed by the air tasking order or ID criteria.", 0),
    ("STARE [laser code, reference point]", "** Cue the laser spot search or tracker function on the specified laser code in relation to the specified reference point. Reference point may include the following: steerpoint, geographic reference, bearing and range, or data link point.", 0),
    ("STATUS [phase]", "1. [A/A] Request for an individual’s tactical situation. & 2. * [A/A] [A/S] Request for amplifying information on current task or aircraft state (e.g., respond with WORKING, JONESING, CONTACT, CAPTURE, TARGETED, LOCKED, ENGAGED", 0),
    ("STRANGER", "[A/A] Unidentified traffic that is not a participant in the action in progress.", 0),
    ("STRANGLE [system]", "[A/A] [S/A] Turn off system indicated (e.g., STRANGLE PARROT).", 0),
    ("STROBE", "[A/A] Radar indication(s) of noise jamming.", 0),
    ("SUPPORT", "** Execute prebriefed support contracts.", 0),
    ("SUPPORTING", "[A/A] Speaking unit or element is assuming a supporting role, is in a position to influence the outcome, and assumes deconfliction responsibility.", 0),
    ("[system] SWEET", "1. [A/A] [S/A] (mode, type) Valid response to an administrative IFF or selective ID feature check request. & 2. (link name) (e.g., TIMBER SWEET) Confirms receipt of data link information. & 3. Equipment indicated is operating efficiently. (Opposite of SOUR; cancels SICK, BENT).", 0),
    ("SWITCH [item]", "1. * Switch the setting on the referenced item. & 2. (POLARITY) Switch IR polarity to black hot or white hot. & 3. * [S/A] Formation or element change to preplanned frequency.", 0),
    ("SWITCHED", "[A/A] Attacker is changing from one aircraft to another.", 0),
    ("SWITCHES SAFE", "MASTER ARM switch is set to SAFE.", 0),
    ("TALLY", "Sighting of a target, non-friendly aircraft, or enemy position. Opposite of NO JOY.", 0),
    ("TARGET", "1. [A/A] [A/S] [S/A] [AIR-MAR] Assignment of targeting responsibilities. & 2. [A/S] [S/S] [AIR-MAR] ROE, PID, coordination of forces, and commander’s guidance requirements on the referenced target or track have been satisfied. Target or track correlation, CDE, and clear field of fire must be accomplished prior to employing ordnance or fires.", 0),
    ("TARGETED", "* [A/A] Fighter has acquired assigned GROUP and has assumed responsibility for it.", 0),
    ("TECHNICAL", "** Improvised fighting vehicle (usually civilian vehicles modified with mounted weapons).", 0),
    ("TEN SECONDS", "[A/S] Standby for (weapon) ON call in approximately 10 seconds.(e.g., LASER ON, TORCH ON, etc.)", 0),
    ("TERMINATE", "[A/A] In training, cease local engagement without affecting the overall exercise.", 0),
    ("THREAT [direction]", "[A/A] Untargeted HOSTILE, BANDIT, or BOGEY is within a briefed range of a FRIENDLY aircraft.", 0),
    ("THROTTLES", "[A/A] Reminder to set throttles appropriately considering the IR threat and desired energy state.", 0),
    ("THUMP", "** [AIR-MAR] Aircraft conducts low-altitude, high-speed pass over or abeam a designated vessel and does not cross the bow. Supersonic airspeed is authorized as long as damage is not anticipated.", 0),
    ("test", "set", 0),
    ("test", "set", 0),
    ("test", "set", 0),
    ("test", "set", 0),
    ("test", "set", 0),
    ("test", "set", 0),

    ("test", "set", 0);

COMMIT TRANSACTION;
