name: Build and Publish image to registry
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build ./bot/ -t ghcr.io/niklasg08/cvw22-operations-officer:latest
      - name: push image to packages
        run: |
          docker login --username niklasg08 --password ${{ secrets.GH_PAT }} ghcr.io
          docker push ghcr.io/niklasg08/cvw22-operations-officer:latest