name: CI/CD for CVW22 Operations Officer Bot
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run:
          flake8 . --count --max-line-length=99 --statistics

  build_and_publish:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build ./bot/ -t ghcr.io/niklasg08/cvw22-operations-officer:latest

      - name: Push Image to Registry
        run: |
          docker login --username niklasg08 --password ${{ secrets.GH_PAT }} ghcr.io
          docker push ghcr.io/niklasg08/cvw22-operations-officer:latest